version: "3.9"
volumes:
  pg_data:
services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
        - "5432"
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
    depends_on:
      - db